const HOST = new URL('.', import.meta.url).href

export default [
  {
    pid: 'editor',
    name: '三维编辑',
    name_en: 'Three Editor',
    order: 20,
    children: [
      {
        id: 'icraft',
        name: 'icraft',
        name_en: 'iCraft Editor',
        tip: 'iCraft编辑器，帮助用户轻松创建令人惊叹的三维建筑图表。',
        author: 'AUTO',
        openUrl: 'https://icraft.design/app/player/dmqSz2F-niKujD94cPb7-Zsa9zIH2Ggt',
        githubUrl: 'https://github.com/gantFDT/icraft',
        image: HOST + 'images/icraft.webp',
      },
      {
        id: 'tiny-world-builder',
        name: 'tiny-world-builder',
        name_en: 'Tiny World Builder',
        tip: '构建微型世界的三维编辑器，支持场景搭建与编辑。',
        author: 'AUTO',
        openUrl: 'https://tinyworld.build/',
        githubUrl: 'https://github.com/jasonkneen/tiny-world-builder',
        image: HOST + 'images/tiny-world-builder.webp',
      },
      {
        id: 'battlefield-editor',
        name: 'Battlefield Editor — AI 戰場編輯器',
        name_en: 'Battlefield Editor — AI 戰場編輯器',
        tip: '数据驱动的历史战役三维编辑器，可加载编排战场演出',
        author: 'AUTO',
        openUrl: 'https://yazelin.github.io/battlefield-editor/',
        githubUrl: 'https://github.com/yazelin/battlefield-editor',
        image: HOST + 'images/battlefield-editor.webp',
      },
      {
        id: 'storyai-3d-director-desk',
        name: '3D导演台-Ai视频',
        name_en: '3D导演台',
        tip: '三维分镜导演台，用于镜头规划与场景摆位。',
        author: 'AUTO',
        openUrl: 'https://github.com/jiguang132/storyai-3d-director-desk',
        githubUrl: 'https://github.com/jiguang132/storyai-3d-director-desk',
        image: HOST + 'images/storyai-3d-director-desk.webp',
      },
      {
        id: 'GNM-Studio',
        name: '人头编辑器',
        name_en: 'GNM-Studio',
        tip: '三维人头模型编辑器，可调整面部特征',
        author: 'AUTO',
        openUrl: 'https://drbaph.is-a.dev/GNM-Studio/',
        githubUrl: 'https://github.com/Saganaki22/GNM-Studio',
        image: HOST + 'images/GNM-Studio.webp',
      }
    ],
  },
  {
    pid: 'digitalTwin',
    name: '数字孪生',
    name_en: 'digitalTwin',
    order: 25,
    children: [
      {
        id: 'PSU-VR',
        name: '室内vr',
        name_en: 'PSU VR',
        tip: '宾州州立大学校园的沉浸式多人虚拟现实体验，复刻真实校园环境。',
        author: 'AUTO',
        openUrl: 'https://psu-vr.herokuapp.com/',
        githubUrl: 'https://github.com/andrewwoan/PSU-VR',
        image: HOST + 'images/PSU-VR.webp',
      },
      {
        id: 'yyhg',
        name: '北京优悦幻光科技',
        name_en: '🍃北京优悦幻光科技 - 数字孪生三维可视化',
        tip: '数字孪生三维可视化项目，打造开源社区，提供专业低成本快速交付方案。',
        author: 'AUTO',
        openUrl: 'https://z2586300277.github.io/yyhg/',
        githubUrl: 'https://github.com/z2586300277/yyhg',
        image: HOST + 'images/yyhg.webp',
      },
      {
        id: 'scenic-digital',
        name: '数字人',
        name_en: '📺 项目展示',
        tip: '智慧文旅数字人体验平台，展示数字孪生技术在文旅场景的应用。',
        author: 'AUTO',
        openUrl: 'https://scenic.yueguichao.cn/#',
        githubUrl: 'https://github.com/front-yue/scenic-digital',
        image: HOST + 'images/scenic-digital.webp',
      },
      {
        id: 'day-night-digital-twins',
        name: '数字校园黑夜白天',
        name_en: '智慧园区',
        tip: '昼夜交替的智慧园区数字孪生场景，展示园区建筑与设施运行状态',
        author: 'AUTO',
        openUrl: 'https://gcat.cc/demo/park',
        githubUrl: 'https://github.com/GhostCatcg/day-night-digital-twins',
        image: HOST + 'images/day-night-digital-twins.webp',
      },
      {
        id: 'my-virtual-world',
        name: 'my-virtual-world',
        name_en: 'My Virtual World',
        tip: '虚拟世界项目，可能涉及数字孪生或园区展示。',
        author: 'AUTO',
        openUrl: 'https://myvirtualworld.ai/',
        githubUrl: 'https://github.com/eliautobot/my-virtual-world',
        image: HOST + 'images/my-virtual-world.webp',
      },
      {
        id: 'Repolis',
        name: 'github 仓库 3D',
        name_en: 'Repolis — the City of Repos',
        tip: '将GitHub仓库转化为可行走的三维城镇，交通塑造建筑，居民生活其中。',
        author: 'AUTO',
        openUrl: 'https://hyeonsangjeon.github.io/Repolis/',
        githubUrl: 'https://github.com/hyeonsangjeon/Repolis',
        image: HOST + 'images/Repolis.webp',
      },
      {
        id: 'jifangDaPing',
        name: '机房大屏',
        name_en: 'threejs-demo',
        tip: '机房大屏三维可视化演示，展示设备与运行状态',
        author: 'AUTO',
        openUrl: 'https://stevenfeng.cn/threejs-demo/',
        githubUrl: 'https://github.com/fh332393900/threejs-demo',
        image: HOST + 'images/jifangDaPing.webp',
      },
      {
        id: 'sewage-treatment-plant',
        name: '污水处理厂',
        name_en: '污水处理厂三维可视化',
        tip: '污水处理厂三维可视化，展示厂区模型、工艺面板与巡检人员。',
        author: 'AUTO',
        openUrl: 'https://sewage-treatment-plant.netlify.app/#/',
        githubUrl: 'https://github.com/cfy1126/sewage-treatment-plant',
        image: HOST + 'images/sewage-treatment-plant.webp',
      },
      {
        id: 'gxu-campus-3d',
        name: '西大 · 云游校园',
        name_en: '西大 · 云游校园',
        tip: '广西大学校园三维游览项目，支持地标搜索、自动巡游与昼夜切换。',
        author: 'AUTO',
        openUrl: 'https://wcqqq1214.github.io/gxu-campus-3d/',
        githubUrl: 'https://github.com/wcqqq1214/gxu-campus-3d',
        image: HOST + 'images/gxu-campus-3d.webp',
      },
      {
        id: 'campus-twin',
        name: '青禾校园 · Vue 数字孪生 Demo',
        name_en: '青禾校园 · Vue 数字孪生 Demo',
        tip: '校园数字孪生演示，含可点击楼宇与告警联动',
        author: 'AUTO',
        openUrl: 'https://g2657.github.io/campus-twin/',
        githubUrl: 'https://github.com/5758703/campus-twin',
        image: HOST + 'images/campus-twin.webp',
      }
    ],
  },
  {
    pid: 'threeMap',
    name: '三维地图',
    name_en: 'Three Map',
    gid: 'commonSeries',
    group: '常用系列',
    group_en: 'Common Series',
    order: 30,
    children: [
      {
        id: 'sat-hunter',
        name: '卫星地图下载',
        name_en: '✨ 主要功能',
        tip: '基于Vue和Leaflet的卫星瓦片底图下载工具。',
        author: 'AUTO',
        openUrl: 'https://knight-l.github.io/sat-hunter/',
        githubUrl: 'https://github.com/knight-L/sat-hunter',
        image: HOST + 'images/sat-hunter.webp',
      },
      {
        id: 'demo-threejs-chinamap',
        name: '下钻地图',
        name_en: 'ThreeJS 实现 3D 地图',
        tip: '三维中国地图示例，支持下钻动画、扩散点、轨迹线、雷达和模型加载。',
        author: 'AUTO',
        openUrl: 'https://github.com/chemistwang/demo-threejs-chinamap',
        githubUrl: 'https://github.com/chemistwang/demo-threejs-chinamap',
        image: HOST + 'images/demo-threejs-chinamap.webp',
      },
      {
        id: 'topoexport',
        name: '框选地图导出白模',
        name_en: 'TopoExporter',
        tip: '桌面工具，选择国家导出过滤后的世界地图数据，用于地理信息处理。',
        author: 'AUTO',
        openUrl: 'https://app.topoexport.com/',
        githubUrl: 'https://github.com/ArunSahadeo/TopoExporter',
        image: HOST + 'images/topoexport.webp',
      },
      {
        id: 'GeoLibre',
        name: 'GeoLibre',
        name_en: 'GeoLibre',
        tip: '开源地理空间数据可视化平台，支持三维地图浏览与插件扩展',
        author: 'AUTO',
        openUrl: 'https://geolibre.app/demo/',
        githubUrl: 'https://github.com/opengeos/GeoLibre',
        image: HOST + 'images/GeoLibre.webp',
      },
      {
        id: 'map3d-build',
        name: '生成3D白膜',
        name_en: 'About The Project',
        tip: '生成真实世界三维地图的工具，支持快速构建地理场景',
        author: 'AUTO',
        openUrl: 'https://map.fleet.im/',
        githubUrl: 'https://github.com/cartesiancs/map3d',
        image: HOST + 'images/map3d-build.webp',
      },
      {
        id: 'lius1314-china-map',
        name: '💎 Three.js 和 Cesium.js 案例 - 为爱发电 - 只做开源 -',
        name_en: '💎 Three.js 和 Cesium.js 案例 - 为爱发电 - 只做开源 -',
        tip: '基于三维引擎实现的中国地图可视化案例，展示地理数据',
        author: 'AUTO',
        openUrl: 'https://www.npmjs.com/package/@lius1314/china-map-3d-designer',
        githubUrl: 'https://github.com/z2586300277/three-cesium-examples',
        image: HOST + 'images/lius1314-china-map.webp',
      },
      {
        id: 'overpass-turbo',
        name: '城市交通路网等geojson',
        name_en: 'overpass-turbo',
        tip: '城市交通路网地理数据可视化，展示道路网络空间分布',
        author: 'AUTO',
        openUrl: 'https://overpass-turbo.eu/',
        githubUrl: 'https://github.com/overpass/overpass-turbo',
        image: HOST + 'images/overpass-turbo.webp',
      },
      {
        id: 'city-roads',
        name: 'city-roads',
        name_en: 'city-roads',
        tip: '一次性渲染任意城市所有道路的在线地图可视化工具。',
        author: 'AUTO',
        openUrl: 'https://anvaka.github.io/city-roads',
        githubUrl: 'https://github.com/anvaka/city-roads',
        image: HOST + 'images/city-roads.webp',
      },
      {
        id: 'seed-westlake',
        name: '山水西湖 · 可交互三维全景',
        name_en: '山水西湖 · 可交互三维全景',
        tip: '豆包模型生成的交互式三维西湖全景地图',
        author: 'AUTO',
        openUrl: 'https://ruanyf.github.io/seed-westlake/',
        githubUrl: 'https://github.com/ruanyf/seed-westlake',
        image: HOST + 'images/seed-westlake.webp',
      },
      {
        id: 'tokyoThree3d',
        name: 'tokyoThree3d',
        name_en: 'Procedural Tokyo',
        tip: '程序化生成东京三维城市模型，可飞行浏览并切换昼夜与动态交通。',
        author: 'AUTO',
        openUrl: 'https://jeantimex.github.io/tokyo/',
        githubUrl: 'https://github.com/jeantimex/tokyo',
        image: HOST + 'images/tokyoThree3d.webp',
      }
    ],
  },
  {
    pid: 'threeCar',
    name: '汽车相关',
    name_en: 'Car Related',
    gid: 'commonSeries',
    group: '常用系列',
    group_en: 'Common Series',
    order: 30,
    children: [
      {
        id: 'bike-demo-threejs',
        name: 'bike-demo-threejs',
        name_en: 'Bike Demo Three.js',
        tip: '展示自行车模型与动画的Three.js演示项目，用于技能展示。',
        author: 'AUTO',
        openUrl: 'https://bike-demo-threejs.vercel.app/',
        githubUrl: 'https://github.com/Kirilbt/bike-demo-threejs',
        image: HOST + 'images/bike-demo-threejs.webp',
      },
      {
        id: 'modkeys',
        name: 'modkeys',
        name_en: 'modkeys',
        tip: '三维键盘电商展示平台，支持在线浏览与选购键盘产品',
        author: 'AUTO',
        openUrl: 'https://modkeys.vercel.app/',
        githubUrl: 'https://github.com/thebuggeddev/modkeys',
        image: HOST + 'images/modkeys.webp',
      },
      {
        id: 'raycast-vehicle',
        name: 'raycast-vehicle',
        name_en: 'Raycast RC Car',
        tip: '基于射线检测的遥控汽车模拟项目',
        author: 'AUTO',
        openUrl: 'https://raycast-rc-car.netlify.app/',
        githubUrl: 'https://github.com/icurtis1/raycast-vehicle',
        image: HOST + 'images/raycast-vehicle.webp',
      },
      {
        id: 'model-x-studio',
        name: 'model-x-studio',
        name_en: 'Model X Studio',
        tip: '特斯拉Model X的交互式3D工作室，展示车辆部件并支持爆炸视图。',
        author: 'AUTO',
        openUrl: 'https://model-x-studio.vercel.app/',
        githubUrl: 'https://github.com/ashemag/model-x-studio',
        image: HOST + 'images/model-x-studio.webp',
      }
    ],
  },
  {
    pid: 'threeEarth',
    name: '三维地球',
    name_en: 'Three Earth',
    gid: 'commonSeries',
    group: '常用系列',
    group_en: 'Common Series',
    order: 30,
    children: [
      {
        id: 'Abdul-Wasay-008',
        name: '太阳系',
        name_en: '🌌 Atlas26',
        tip: '实时交互式三维太空可视化平台，帮助用户探索和理解宇宙。',
        author: 'AUTO',
        openUrl: 'https://atlas26.vercel.app/dashboard',
        githubUrl: 'https://github.com/Abdul-Wasay-008/Atlas26',
        image: HOST + 'images/Abdul-Wasay-008.webp',
      },
      {
        id: 'little-city',
        name: '🌏 Little Taipei 台北',
        name_en: '🌏 Little Taipei 台北',
        tip: '将台北地标按真实方位距离构建成可探索的微型星球，浏览器中运行。',
        author: 'AUTO',
        openUrl: 'https://antics.gg/world/little-taipei',
        githubUrl: 'https://github.com/craftmygame/little-city',
        image: HOST + 'images/little-city.webp',
      },
      {
        id: 'gods-eye-view',
        name: 'gods-eye-view',
        name_en: '🌐 God\'s Eye View',
        tip: '上帝视角三维地球可视化项目，展示全球地理信息与动态效果。',
        author: 'AUTO',
        openUrl: 'https://maptheworld.ai/',
        githubUrl: 'https://github.com/bilawalsidhu/gods-eye-view',
        image: HOST + 'images/gods-eye-view.webp',
      }
    ],
  },
  {
    pid: 'gaussianSplatter',
    name: '高斯泼溅',
    name_en: 'Gaussian Splatter',
    order: 35,
    children: [
      {
        id: 'third-person-controller-splat',
        name: '高斯漫游',
        name_en: '3rd-Person Character Controller — Spark 2.0 LoD ',
        tip: '基于高斯泼溅与物理引擎的第三人称角色控制器。',
        author: 'AUTO',
        openUrl: 'https://third-person-character-controller.netlify.app/',
        githubUrl: 'https://github.com/icurtis1/third-person-controller-splat',
        image: HOST + 'images/aa.webp',
      },
      {
        id: 'marble-runner',
        name: 'marble-runner',
        name_en: 'Marble Runner',
        tip: '在高斯泼溅世界中以第三人称视角行走探索。',
        author: 'AUTO',
        openUrl: 'https://marble-runner.vercel.app/',
        githubUrl: 'https://github.com/panterathehacker/marble-runner',
        image: HOST + 'images/marble-runner.webp',
      },
      {
        id: 'aholo-viewer',
        name: '高斯渲染',
        name_en: 'Aholo Viewer',
        tip: '用于查看和转换高斯泼溅数据的查看器组件。',
        author: 'AUTO',
        openUrl: 'https://aholojs.dev/zh-CN/',
        githubUrl: 'https://github.com/manycoretech/aholo-viewer',
        image: HOST + 'images/aholo-viewer.webp',
      }
    ],
  },
  {
    pid: 'gameExamples',
    name: '游戏案例',
    name_en: 'Game Examples',
    order: 45,
    children: [
      {
        id: 'zen-robot-garden',
        name: '割草机器人',
        name_en: 'Zen Robot Garden 🤖🌿',
        tip: '浏览器中的三维禅意花园游戏，割草机器人自动工作，可静静观赏。',
        author: 'AUTO',
        openUrl: 'https://robin7331.github.io/zen-robot-garden/',
        githubUrl: 'https://github.com/robin7331/zen-robot-garden',
        image: HOST + 'images/zen-robot-garden.webp',
      },
      {
        id: 'gta7',
        name: 'gta7',
        name_en: 'GTA 7 🚗🌃',
        tip: '基于Three.js的开放世界游戏演示，可驾驶车辆探索城市，体验自由玩法',
        author: 'AUTO',
        openUrl: 'https://depixeled-chris.github.io/gta7/',
        githubUrl: 'https://github.com/depixeled-chris/gta7',
        image: HOST + 'images/gta7.webp',
      },
      {
        id: 'cat-planet',
        name: 'cat-planet',
        name_en: 'Cat Planet',
        tip: '互动式三维猫咪图鉴，包含喂养、探索品种起源和分享时刻的趣味体验。',
        author: 'AUTO',
        openUrl: 'https://qq598516797-dotcom.github.io/cat-planet/',
        githubUrl: 'https://github.com/qq598516797-dotcom/cat-planet',
        image: HOST + 'images/cat-planet.webp',
      },
      {
        id: 'house-builder',
        name: 'house-builder',
        name_en: 'Three.js Sims-like House Builder',
        tip: '类似模拟人生的房屋建造器，在浏览器中自由设计和搭建三维房屋。',
        author: 'AUTO',
        openUrl: 'https://ch-bas.github.io/threejs-sims-house-builder/',
        githubUrl: 'https://github.com/ch-bas/threejs-sims-house-builder',
        image: HOST + 'images/house-builder.webp',
      },
      {
        id: 'vrm-game',
        name: 'vrm-游戏',
        name_en: 'VRM Game Starter',
        tip: '使用VRM角色和Three.js构建3D游戏的入门模板，包含可操作角色和',
        author: 'AUTO',
        openUrl: 'https://norio.github.io/vrm-game-starter/',
        githubUrl: 'https://github.com/norio/vrm-game-starter',
        image: HOST + 'images/vrm-game.webp',
      },
      {
        id: 'rubiks-rubrics',
        name: 'rubiks-rubrics',
        name_en: 'Rubik\'s Rubrics',
        tip: '3D魔方可视化与求解器，支持摄像头扫描真实魔方并展示解法动画。',
        author: 'AUTO',
        openUrl: 'https://leereilly.net/rubiks-rubrics/',
        githubUrl: 'https://github.com/leereilly/rubiks-rubrics',
        image: HOST + 'images/rubiks-rubrics.webp',
      },
      {
        id: 'procedural-spider',
        name: 'procedural-spider',
        name_en: '🕷️ Procedural Spider',
        tip: '程序化生成蜘蛛角色，用逆运动学实现自适应地形行走',
        author: 'AUTO',
        openUrl: 'https://proceduralspider.netlify.app/',
        githubUrl: 'https://github.com/majidmanzarpour/threejs-procedural-spider',
        image: HOST + 'images/procedural-spider.webp',
      },
      {
        id: 'RippleAquarium',
        name: '🐠 涟漪鱼缸',
        name_en: '🐠 涟漪鱼缸',
        tip: '纯前端WebGL水族箱，模拟鱼群与实时水面涟漪效果。',
        author: 'AUTO',
        openUrl: 'https://seanwong17.github.io/RippleAquarium/',
        githubUrl: 'https://github.com/SeanWong17/RippleAquarium',
        image: HOST + 'images/RippleAquarium.webp',
      },
      {
        id: 'threejs-procedural-dungeon',
        name: 'threejs-procedural-dungeon',
        name_en: '🏰 Dungeon Forge',
        tip: '程序化地牢生成器，可观看房间与走廊的构建过程。',
        author: 'AUTO',
        openUrl: 'https://procedural-dungeon.netlify.app/',
        githubUrl: 'https://github.com/majidmanzarpour/threejs-procedural-dungeon',
        image: HOST + 'images/threejs-procedural-dungeon.webp',
      },
      {
        id: 'skyline-run',
        name: 'skyline-run',
        name_en: '✈️ Skyline Run',
        tip: '驾驶飞机穿越GitHub提交记录的可玩飞行游戏',
        author: 'AUTO',
        openUrl: 'https://skyline-run.vercel.app',
        githubUrl: 'https://github.com/anshaneja5/skyline-run',
        image: HOST + 'images/skyline-run.webp',
      },
      {
        id: 'utsuwa',
        name: 'LLM 数字人',
        name_en: 'Features',
        tip: 'Utsuwa游戏项目，包含可玩内容',
        author: 'AUTO',
        openUrl: 'https://www.utsuwa.ai/',
        githubUrl: 'https://github.com/The-Lab-by-Ordinary-Company/utsuwa',
        image: HOST + 'images/utsuwa.webp',
      },
      {
        id: 'operation-ironhold',
        name: 'operation-ironhold',
        name_en: 'Operation Ironhold',
        tip: '单文件浏览器第一人称射击游戏，无需构建步骤和外部资源文件。',
        author: 'AUTO',
        openUrl: 'https://starknightt.github.io/operation-ironhold/',
        githubUrl: 'https://github.com/StarKnightt/operation-ironhold',
        image: HOST + 'images/operation-ironhold.webp',
      },
      {
        id: 'TheLongSilence',
        name: 'TheLongSilence',
        name_en: 'THE LONG SILENCE',
        tip: '程序化太空探索游戏，基于种子生成恒星、行星与星云，浏览器直接运行。',
        author: 'AUTO',
        openUrl: 'https://www.3dgenstudio.com/',
        githubUrl: 'https://github.com/achimala/TheLongSilence',
        image: HOST + 'images/TheLongSilence.webp',
      },
      {
        id: 'jungle-trail',
        name: 'jungle-trail',
        name_en: 'Jungle Trail',
        tip: '第一人称丛林小径探险，所有纹理模型音效均程序生成',
        author: 'AUTO',
        openUrl: 'https://starknightt.github.io/jungle-trail/',
        githubUrl: 'https://github.com/StarKnightt/jungle-trail',
        image: HOST + 'images/jungle-trail.webp',
      },
      {
        id: 'pallet-town-3d',
        name: 'pallet-town-3d',
        name_en: 'Pallet Town',
        tip: '宝可梦真新镇三维卡通重制，第一人称选择初始伙伴',
        author: 'AUTO',
        openUrl: 'https://pallet-town-3d-one.vercel.app/',
        githubUrl: 'https://github.com/PauliusOS/pallet-town-3d',
        image: HOST + 'images/pallet-town-3d.webp',
      },
      {
        id: 'footballThree',
        name: 'footballThree',
        name_en: 'footballThree',
        tip: '无尽草原足球游戏，实时操控球员进行射门对抗',
        author: 'AUTO',
        openUrl: 'https://football-ashy-rho.vercel.app/',
        githubUrl: 'https://github.com/thebuggeddev/football',
        image: HOST + 'images/footballThree.webp',
      },
      {
        id: 'moon-rover',
        name: 'moon-rover',
        name_en: 'REGOLITH',
        tip: '月球车勘测游戏，在浏览器中驾驶巡视并收集样本',
        author: 'AUTO',
        openUrl: 'https://winchxyz.github.io/moon-rover/',
        githubUrl: 'https://github.com/winchxyz/moon-rover',
        image: HOST + 'images/moon-rover.webp',
      },
      {
        id: 'SamuraiThirdPersonTemplateThreeJS',
        name: 'SamuraiThirdPersonTemplateThreeJS',
        name_en: 'Samurai — a third-person Three.js template',
        tip: '第三人称武士动作模板，含移动、近战、飞行与装备系统',
        author: 'AUTO',
        openUrl: 'https://g2657.github.io/SamuraiThirdPersonTemplateThreeJS/',
        githubUrl: 'https://github.com/achrefelouafi/SamuraiThirdPersonTemplateThreeJS',
        image: HOST + 'images/SamuraiThirdPersonTemplateThreeJS.webp',
      },
      {
        id: 'AvatarCastingAbilitiesThreeJS',
        name: 'AvatarCastingAbilitiesThreeJS',
        name_en: 'Bending Sandbox',
        tip: '基于Three.js的元素技能沙盒，绘制路径释放火水地气技能并爆炸。',
        author: 'AUTO',
        openUrl: 'https://g2657.github.io/AvatarCastingAbilitiesThreeJS/',
        githubUrl: 'https://github.com/achrefelouafi/AvatarCastingAbilitiesThreeJS',
        image: HOST + 'images/AvatarCastingAbilitiesThreeJS.webp',
      },
      {
        id: 'LinearAbiltyCastingThreeJS',
        name: 'LinearAbiltyCastingThreeJS',
        name_en: 'Elemental Sandbox',
        tip: '基于Three.js的技能射击特效沙盒，使用手写着色器实现元素技能。',
        author: 'AUTO',
        openUrl: 'https://g2657.github.io/LinearAbiltyCastingThreeJS/',
        githubUrl: 'https://github.com/achrefelouafi/LinearAbiltyCastingThreeJS',
        image: HOST + 'images/LinearAbiltyCastingThreeJS.webp',
      },
      {
        id: 'Claude-of-Tanks',
        name: 'Claude-of-Tanks',
        name_en: 'Fight, inspect, and direct',
        tip: '坦克战斗模拟器，包含装甲、弹道与物理，多智能体构建。',
        author: 'AUTO',
        openUrl: 'https://cot.kevinliu.studio/',
        githubUrl: 'https://github.com/Kevin-Liu-01/Claude-of-Tanks',
        image: HOST + 'images/Claude-of-Tanks.webp',
      },
      {
        id: 'gogh-strike',
        name: 'gogh-strike',
        name_en: 'Gogh Strike',
        tip: '艺术对决游戏，十二位艺术家分成两队进行颜料大战。',
        author: 'AUTO',
        openUrl: 'https://gogh-strike.surge.sh/',
        githubUrl: 'https://github.com/petergpt/gogh-strike',
        image: HOST + 'images/gogh-strike.webp',
      },
      {
        id: 'blacksite_fps',
        name: 'blacksite_fps',
        name_en: 'blacksite_fps',
        tip: '基于Three.js的波次生存第一人称射击游戏，使用Rapier物理。',
        author: 'AUTO',
        openUrl: 'https://blacksite-one.vercel.app/',
        githubUrl: 'https://github.com/Hiraeth010/blacksite',
        image: HOST + 'images/blacksite_fps.webp',
      },
      {
        id: 'chinese-chess',
        name: '中國象棋 · Three.js 3D',
        name_en: '中國象棋 · Three.js 3D',
        tip: '基于Three.js的3D中国象棋游戏，支持人机对战和双人热座，包含完整',
        author: 'AUTO',
        openUrl: 'https://chinese-chess.gh.miniasp.com/',
        githubUrl: 'https://github.com/doggy8088/chinese-chess',
        image: HOST + 'images/chinese-chess.webp',
      },
      {
        id: 'mosswing-quiet-flight',
        name: 'GPT-6 Astra · One Shot 游戏测试',
        name_en: 'GPT-6 Astra · One Shot 游戏测试',
        tip: '通过两次一次性提示测试GPT-6 Astra的游戏设计与实现能力，保留原',
        author: 'AUTO',
        openUrl: 'https://mosswing-quiet-flight.jack-514.chatgpt.site/',
        githubUrl: 'https://github.com/Ayi1337/gpt6-astra-one-shot-games',
        image: HOST + 'images/mosswing-quiet-flight.webp',
      },
      {
        id: 'melon-game',
        name: 'melon-game.jack',
        name_en: 'GPT-6 Astra · One Shot 游戏测试',
        tip: '通过两次一次性提示测试GPT-6 Astra的游戏设计与实现能力，保留原',
        author: 'AUTO',
        openUrl: 'https://melon-game.jack-514.chatgpt.site/',
        githubUrl: 'https://github.com/Ayi1337/gpt6-astra-one-shot-games',
        image: HOST + 'images/melon-game.jack.webp',
      },
      {
        id: 'Othello',
        name: 'Othello',
        name_en: 'Flip Buddies',
        tip: '一个友好的黑白棋游戏，带有动画角色，支持与电脑或朋友对战。',
        author: 'AUTO',
        openUrl: 'https://flipbuddies.vladpalacio.com/',
        githubUrl: 'https://github.com/deifos/Othello',
        image: HOST + 'images/Othello.webp',
      },
      {
        id: 'hit-and-run-web',
        name: 'hit-and-run-web',
        name_en: 'Hit & Run in the browser',
        tip: '浏览器中重建辛普森跑酷游戏，无需模拟器即可体验原版剧情与竞速。',
        author: 'AUTO',
        openUrl: 'https://vheissu.github.io/hit-and-run-web/',
        githubUrl: 'https://github.com/Vheissu/hit-and-run-web',
        image: HOST + 'images/hit-and-run-web.webp',
      },
      {
        id: 'LinearAbiltyCastingExtendedThreeJS',
        name: 'LinearAbiltyCastingExtendedThreeJS',
        name_en: 'Elemental Sandbox',
        tip: '基于Three.js与手写着色器的元素技能特效沙盒，可自由组合释放。',
        author: 'AUTO',
        openUrl: 'https://g2657.github.io/LinearAbiltyCastingExtendedThreeJS/',
        githubUrl: 'https://github.com/achrefelouafi/LinearAbiltyCastingExtendedThreeJS',
        image: HOST + 'images/LinearAbiltyCastingExtendedThreeJS.webp',
      },
      {
        id: 'tihuqiche',
        name: '鹈鹕骑车 · Pelican Pedal Run',
        name_en: '鹈鹕骑车 · Pelican Pedal Run',
        tip: '鹈鹕骑车是一款3D闯关游戏，支持双人合作与多种模式，穿越全球城市。',
        author: 'AUTO',
        openUrl: 'https://tihuqiche.com/',
        githubUrl: 'https://github.com/Licoy/tihuqiche',
        image: HOST + 'images/tihuqiche.webp',
      },
      {
        id: 'steel-defense',
        name: '钢铁防线：异星入侵 · 试玩版',
        name_en: '钢铁防线：异星入侵 · 试玩版',
        tip: '月面基地保卫战游戏，操控机器人抵御三波外星入侵并升级装备。',
        author: 'AUTO',
        openUrl: 'https://kingkk469.github.io/steel-defense/',
        githubUrl: 'https://github.com/kingkk469/steel-defense',
        image: HOST + 'images/steel-defense.webp',
      },
      {
        id: 'zork-underground-empire',
        name: 'zork-underground-empire',
        name_en: 'Zork — The Great Underground Empire',
        tip: '第一人称三维版Zork冒险游戏，探索地下帝国并收集十九件宝藏。',
        author: 'AUTO',
        openUrl: 'https://zork-underground-empire.netlify.app/',
        githubUrl: 'https://github.com/emollick/zork-underground-empire',
        image: HOST + 'images/zork-underground-empire.webp',
      },
      {
        id: 'paper-aquarium',
        name: 'paper-aquarium',
        name_en: 'Paper Aquarium',
        tip: '儿童涂色拍照后鱼在屏幕水族箱游动的家庭游戏',
        author: 'AUTO',
        openUrl: 'https://aquarium.mrmot9i.com/',
        githubUrl: 'https://github.com/MrMoT9I/paper-aquarium',
        image: HOST + 'images/paper-aquarium.webp',
      },
      {
        id: 'pelican-bike',
        name: '这个仓库是什么',
        name_en: '这个仓库是什么',
        tip: '一句提示词生成三个可玩三维网页游戏',
        author: 'AUTO',
        openUrl: 'https://claude-opus-5-5.riba2534.cn/',
        githubUrl: 'https://github.com/riba2534/claude-opus-5-5-demo',
        image: HOST + 'images/pelican-bike.webp',
      },
      {
        id: 'tidewater',
        name: 'tidewater',
        name_en: 'Tidewater',
        tip: '浏览器海岛钓鱼游戏，含实时海洋与船只驾驶',
        author: 'AUTO',
        openUrl: 'https://dgreenheck.github.io/tidewater/',
        githubUrl: 'https://github.com/dgreenheck/tidewater',
        image: HOST + 'images/tidewater.webp',
      },
      {
        id: 'grand-atelier',
        name: 'grand-atelier',
        name_en: 'Grand Atelier',
        tip: '浏览器中可弹奏的三角钢琴交互作品',
        author: 'AUTO',
        openUrl: 'https://piano.anionex.me/',
        githubUrl: 'https://github.com/Anionex/grand-atelier',
        image: HOST + 'images/grand-atelier.webp',
      },
      {
        id: 'voxel-musou',
        name: 'voxel-musou',
        name_en: 'Features',
        tip: '体素风格一骑当千动作割草游戏',
        author: 'AUTO',
        openUrl: 'https://voxel-musou.vercel.app/',
        githubUrl: 'https://github.com/mike007jd/voxel-musou',
        image: HOST + 'images/voxel-musou.webp',
      },
      {
        id: 'inkwaveThree',
        name: 'inkwaveThree',
        name_en: 'Features',
        tip: '喷射战士风格四对四涂地射击游戏',
        author: 'AUTO',
        openUrl: 'https://inkwave-aah.pages.dev/',
        githubUrl: 'https://github.com/jaydendavisnc/inkwave',
        image: HOST + 'images/inkwaveThree.webp',
      },
      {
        id: 'little-flock',
        name: 'Little Flock · 小羊慢慢',
        name_en: 'Little Flock · 小羊慢慢',
        tip: '温馨多人牧羊游戏，玩家可协作经营羊群，体验轻松农场生活。',
        author: 'AUTO',
        openUrl: 'https://sharpherd.song.work/',
        githubUrl: 'https://github.com/songkeys/little-flock',
        image: HOST + 'images/little-flock.webp',
      },
      {
        id: 'AbilityCastingThreeJS',
        name: 'AbilityCastingThreeJS',
        name_en: 'Elemental Sandbox',
        tip: '实时元素法术沙盒，手写着色器与物理模拟，可调节千种参数。',
        author: 'AUTO',
        openUrl: 'https://abilitycastingthreejs.chirostudio.xyz/',
        githubUrl: 'https://github.com/achrefelouafi/AbilityCastingThreeJS',
        image: HOST + 'images/AbilityCastingThreeJS.jpg',
      }
    ],
  },
  {
    pid: 'aiFor3D',
    name: 'Ai应用',
    name_en: 'Ai Applications',
    gid: 'advancedExamples',
    group: '高级案例',
    group_en: 'Advanced Examples',
    order: 50,
    children: [
      {
        id: 'off-axis-sneaker',
        name: '图像识别控制',
        name_en: 'Head-Coupled Perspective Viewer',
        tip: '利用面部追踪调整相机透视，实现头耦合立体效果。',
        author: 'AUTO',
        openUrl: 'https://off-axis-sneaker.bolt.host/',
        githubUrl: 'https://github.com/icurtis1/off-axis-sneaker',
        image: HOST + 'images/off-axis-sneaker.webp',
      },
      {
        id: 'articraft',
        name: 'ai 建模动画',
        name_en: 'Quickstart',
        tip: '生成并查看铰接式三维资产的智能工具。',
        author: 'AUTO',
        openUrl: 'https://articraft3d.github.io/#overview',
        githubUrl: 'https://github.com/mattzh72/articraft',
        image: HOST + 'images/articraft.webp',
      },
      {
        id: 'SysMocap',
        name: '数字虚拟人',
        name_en: 'SysMocap',
        tip: '跨平台实时视频驱动动作捕捉与三维虚拟角色渲染系统，用于虚拟主播。',
        author: 'AUTO',
        openUrl: 'https://github.com/xianfei/SysMocap',
        githubUrl: 'https://github.com/xianfei/SysMocap',
        image: HOST + 'images/SysMocap.webp',
      },
      {
        id: 'ABot-Earth',
        name: 'ABot-Earth',
        name_en: 'ABot-Earth-0.5',
        tip: '高德推出的地球智能体模型，用于地理空间任务理解与推理',
        author: 'AUTO',
        openUrl: 'https://abot-earth.amap.com/',
        githubUrl: 'https://github.com/amap-cvlab/ABot-Earth-0.5',
        image: HOST + 'images/ABot-Earth.webp',
      },
      {
        id: 'HiCAD',
        name: 'HiCAD',
        name_en: '⬡ HiCAD',
        tip: '自然语言生成可3D打印的参数化模型，秒级完成。',
        author: 'AUTO',
        openUrl: 'https://hicad.mvtable.com/',
        githubUrl: 'https://github.com/MrXujiang/HiCAD',
        image: HOST + 'images/HiCAD.webp',
      },
      {
        id: 'ApexForge',
        name: 'AI 建模',
        name_en: '为什么做 ApexForge',
        tip: 'AI驱动的实时3D CAD工作台，自然语言生成模型。',
        author: 'AUTO',
        openUrl: 'http://apexforge.turntip.cn/',
        githubUrl: 'https://github.com/MrXujiang/ApexForge',
        image: HOST + 'images/ApexForge.webp',
      },
      {
        id: 'Three-Object-Sculptor',
        name: 'codexthreejs 插件',
        name_en: 'img2obj',
        tip: '将参考图像转化为可动画的程序化三维物体。',
        author: 'AUTO',
        openUrl: 'https://3dship.harrysoftware.com/',
        githubUrl: 'https://github.com/vinhhien112/Three.js-Object-Sculptor-Codex-Plugin',
        image: HOST + 'images/Three.js-Object-Sculptor-Codex-Plugin.webp',
      },
      {
        id: 'ThreejsGNM',
        name: '头编辑器',
        name_en: 'Three.js GNM Head Editor',
        tip: '浏览器端人头编辑器，支持身份表情姿态校正',
        author: 'AUTO',
        openUrl: 'https://threejs-gnm.vercel.app/',
        githubUrl: 'https://github.com/ademola-lou/ThreejsGNM',
        image: HOST + 'images/ThreejsGNM.webp',
      },
      {
        id: 'img2threejs',
        name: '图像转3D',
        name_en: 'img2threejs',
        tip: '将参考图像重建为纯代码程序化Three.js模型',
        author: 'AUTO',
        openUrl: 'https://hoainho.github.io/img2threejs-showcase/',
        githubUrl: 'https://github.com/hoainho/img2threejs',
        image: HOST + 'images/img2threejs.webp',
      },
      {
        id: 'threejs-sculpt-dna',
        name: 'threejs-sculpt-dna',
        name_en: 'threejs-sculpt-dna — A GitHub Copilot Plugin',
        tip: '利用智能助手将参考图转为可编辑三维代码的插件',
        author: 'AUTO',
        openUrl: 'https://hyeonsangjeon.github.io/threejs-sculpt-dna/',
        githubUrl: 'https://github.com/hyeonsangjeon/threejs-sculpt-dna',
        image: HOST + 'images/threejs-sculpt-dna.webp',
      },
      {
        id: '3d-life-sim',
        name: '3d-life-sim',
        name_en: '3D Life Sim',
        tip: '基于网页图形接口的粒子生命模拟，呈现涌现群集结构',
        author: 'AUTO',
        openUrl: 'https://3d-life-sim.pages.dev/',
        githubUrl: 'https://github.com/kajukabla/3d-life-sim',
        image: HOST + 'images/3d-life-sim.webp',
      },
      {
        id: 'kindergrimm',
        name: 'kindergrimm',
        name_en: 'drawai',
        tip: '程序化生成涂鸦角色，每骨骼绑定一个部位，可用于游戏动画。',
        author: 'AUTO',
        openUrl: 'https://kindergrimm.vercel.app/',
        githubUrl: 'https://github.com/albertobeiz/kindergrimm',
        image: HOST + 'images/kindergrimm.webp',
      },
      {
        id: 'GeometryPainterThreeJS',
        name: 'GeometryPainterThreeJS',
        name_en: '💎 Geometry Painter — three.js WebGPU',
        tip: '基于WebGPU的几何绘画工具，在球面绘制晶体脉络。',
        author: 'AUTO',
        openUrl: 'https://g2657.github.io/GeometryPainterThreeJS/',
        githubUrl: 'https://github.com/achrefelouafi/GeometryPainterThreeJS',
        image: HOST + 'images/GeometryPainterThreeJS.webp',
      },
      {
        id: 'awesome-gpt-6-dav',
        name: 'awesome-gpt-6-dav',
        name_en: 'Awesome GPT-6 Astra',
        tip: '整理GPT-6 Astra相关项目、演示和集成，突出计算机使用和空间推理',
        author: 'AUTO',
        openUrl: 'https://github.com/archorfight/awesome-gpt-6-astra#viral-demos',
        githubUrl: 'https://github.com/archorfight/awesome-gpt-6-astra#viral-demos',
        image: HOST + 'images/awesome-gpt-6-dav.webp',
      },
      {
        id: 'mixamo-llm-mocap',
        name: 'mixamo-llm-mocap',
        name_en: 'Mixamo LLM Mocap',
        tip: '利用大语言模型将普通视频转为Mixamo角色动画，无需动捕设备。',
        author: 'AUTO',
        openUrl: 'https://github.com/squall01337/mixamo-llm-mocap',
        githubUrl: 'https://github.com/squall01337/mixamo-llm-mocap',
        image: HOST + 'images/mixamo-llm-mocap.webp',
      }
    ],
  },
  {
    pid: 'industryWorks',
    name: '行业作品',
    name_en: 'Industry Works',
    gid: 'advancedExamples',
    group: '高级案例',
    group_en: 'Advanced Examples',
    order: 55,
    children: [
      {
        id: 'LearningCell',
        name: '细胞课堂',
        name_en: '细胞结构工坊 · Cell Architecture Studio',
        tip: '面向中文课堂的交互式三维生物教学网页，可旋转缩放观察细胞分子模型。',
        author: 'AUTO',
        openUrl: 'https://gordensun.github.io/LearningCell/',
        githubUrl: 'https://github.com/GordenSun/LearningCell',
        image: HOST + 'images/LearningCell.webp',
      },
      {
        id: 'sooahs-room-folio',
        name: '房间',
        name_en: '💜 수아\'s Award-Winning Room Folio 💜',
        tip: '获奖的房间作品集网站，展示三维空间设计，适合初学者学习参考。',
        author: 'AUTO',
        openUrl: 'https://www.sooahs-room-folio.com/',
        githubUrl: 'https://github.com/andrewwoan/sooahs-room-folio',
        image: HOST + 'images/sooahs-room-folio.webp',
      },
      {
        id: 'DeviceShowcase',
        name: '电脑',
        name_en: '3D Device Demo with Threepipe',
        tip: '使用Threepipe构建的极简三维网站，在交互环境中展示笔记本和手机设',
        author: 'AUTO',
        openUrl: 'https://tympanus.net/Tutorials/DeviceShowcase/',
        githubUrl: 'https://github.com/repalash/threepipe-device-mockup-codrops',
        image: HOST + 'images/DeviceShowcase.webp',
      },
      {
        id: 'bellas-park',
        name: '公园',
        name_en: '💁🏻‍♀️ Bella Xu\'s Award-Winning Folio 🏃🏻‍♀️',
        tip: '获奖的三维作品集网站，使用Three.js和Blender创建，适合创意',
        author: 'AUTO',
        openUrl: 'https://www.bellas-park.com/',
        githubUrl: 'https://github.com/andrewwoan/bellas-park',
        image: HOST + 'images/bellas-park.webp',
      },
      {
        id: 'Interactive-Styling-Canvas',
        name: '切换衣服',
        name_en: 'Interactive Styling Canvas',
        tip: '拖拽虚拟T恤到模型上即时更换外观的交互展示。',
        author: 'AUTO',
        openUrl: 'https://tympanus.net/Development/InteractiveStylingUI/',
        githubUrl: 'https://github.com/kaberikram/Interactive-Styling-Canvas',
        image: HOST + 'images/Interactive-Styling-Canvas.webp',
      },
      {
        id: 'r3f-unshift-effect',
        name: 'unshift-effect',
        name_en: 'About',
        tip: '复现unshift作品页面特效的交互式三维场景。',
        author: 'AUTO',
        openUrl: 'https://nemutas.github.io/r3f-unshift-effect/',
        githubUrl: 'https://github.com/nemutas/r3f-unshift-effect',
        image: HOST + 'images/r3f-unshift-effect.webp',
      },
      {
        id: 'comfort-website',
        name: '3d主页网站',
        name_en: '💑 John and Patricia\'s Couple\'s Therapy Website ',
        tip: '结合Blender和Three.js构建的情侣治疗展示网站。',
        author: 'AUTO',
        openUrl: 'https://john-and-patricias-romantic-comfort.vercel.app/',
        githubUrl: 'https://github.com/andrewwoan/john-and-patricias-romantic-comfort-website',
        image: HOST + 'images/comfort-website.webp',
      },
      {
        id: 'cymatics-labs',
        name: '音频粒子',
        name_en: 'Cymatics Labs',
        tip: '实时声波图案模拟器，通过粒子物理将声音可视化，内置多种预设。',
        author: 'AUTO',
        openUrl: 'https://cymatics-labs.vercel.app/',
        githubUrl: 'https://github.com/Sidmaz666/cymatics-labs',
        image: HOST + 'images/cymatics-labs.webp',
      },
      {
        id: 'tang-changan',
        name: '大唐长安 · Tang Chang\'an Diorama (V11)',
        name_en: '大唐长安 · Tang Chang\'an Diorama (V11)',
        tip: '大唐长安历史沙盘，可漫游、对话、吟诗、游戏，体验盛唐百年变迁。',
        author: 'AUTO',
        openUrl: 'https://github.com/andyhuo520/tang-changan',
        githubUrl: 'https://github.com/andyhuo520/tang-changan',
        image: HOST + 'images/tang-changan.webp',
      },
      {
        id: 'Rose_flower',
        name: 'Rose_flower',
        name_en: 'Rose flower',
        tip: '程序化生成的三维发光玫瑰，使用自定义着色器和泛光效果，无需外部模型。',
        author: 'AUTO',
        openUrl: 'https://wake-bikila-dev.github.io/Rose_flower/',
        githubUrl: 'https://github.com/wake-bikila-dev/Rose_flower',
        image: HOST + 'images/Rose_flower.webp',
      },
      {
        id: 'fable5world',
        name: 'fable5world',
        name_en: 'LAAS',
        tip: '展示古老森林的3D场景作品，可能用于环境艺术或自然模拟。',
        author: 'AUTO',
        openUrl: 'https://dc5fzrbo8ssfx.cloudfront.net/laas/',
        githubUrl: 'https://github.com/Braffolk/fable5-world-demo',
        image: HOST + 'images/fable5world.webp',
      },
      {
        id: 'messenger-copy',
        name: 'messenger-copy',
        name_en: 'messenger-copy',
        tip: '复刻Messenger场景的学习项目，包含材质着色器与场景结构',
        author: 'AUTO',
        openUrl: 'https://messenger.abeto.co/',
        githubUrl: 'https://github.com/arafays/messenger-copy',
        image: HOST + 'images/messenger-copy.webp',
      },
      {
        id: 'de-bees',
        name: 'de-bees',
        name_en: 'The Apiary Ledger of Delaware',
        tip: '特拉华州养蜂人图鉴，以等距地图展示蜂场与蜂蜜品种信息',
        author: 'AUTO',
        openUrl: 'https://de-bees.vercel.app/',
        githubUrl: 'https://github.com/snyderb-de/de-bees',
        image: HOST + 'images/de-bees.jpg',
      },
      {
        id: 'ThreeJS_Portfolio',
        name: 'ThreeJS_Portfolio',
        name_en: 'GitHub Star Tree',
        tip: '三维作品集场景，将代码仓库星标转化为树屋村落可视化',
        author: 'AUTO',
        openUrl: 'https://three-js-portfolio-rust-beta.vercel.app/',
        githubUrl: 'https://github.com/Plattnericus/ThreeJS_Portfolio',
        image: HOST + 'images/ThreeJS_Portfolio.webp',
      },
      {
        id: 'ode-to-yosemite',
        name: 'ode-to-yosemite',
        name_en: 'Ode to Yosemite',
        tip: '以优胜美地自然风光为主题的三维场景展示作品，呈现山川地貌',
        author: 'AUTO',
        openUrl: 'https://ode-to-yosemite.vercel.app/',
        githubUrl: 'https://github.com/shlokkhemani/ode-to-yosemite',
        image: HOST + 'images/ode-to-yosemite.webp',
      },
      {
        id: 'weisdevice-project',
        name: 'weisdevice-project',
        name_en: 'Weisdevice Portfolio',
        tip: '个人作品集网站，融合三维图形与动画技术展示设计项目',
        author: 'AUTO',
        openUrl: 'https://www.weisdevice.xyz/',
        githubUrl: 'https://github.com/wehwayne2/weisdevice-project',
        image: HOST + 'images/weisdevice-project.webp',
      },
      {
        id: 'china-heritage-3d',
        name: '中国古建筑瑰宝 3D',
        name_en: '中国古建筑瑰宝 3D',
        tip: '中国古建筑三维展示，卷轴界面呈现七座代表性建筑。',
        author: 'AUTO',
        openUrl: 'https://architecture-iota-khaki.vercel.app/',
        githubUrl: 'https://github.com/xyiqq/china-heritage-3d',
        image: HOST + 'images/china-heritage-3d.webp',
      },
      {
        id: 'KallkaGoMy_website',
        name: 'KallkaGoMy_website',
        name_en: 'My_website',
        tip: '使用React、Three.js和Vite构建的个人主页',
        author: 'AUTO',
        openUrl: 'https://my-website-kallka.vercel.app/#work',
        githubUrl: 'https://github.com/KallkaGo/My_website',
        image: HOST + 'images/KallkaGoMy_website.webp',
      },
      {
        id: 'paper-roll',
        name: 'paper-roll',
        name_en: 'paper-roll',
        tip: '无限物理滚动的纸带展示作品集',
        author: 'AUTO',
        openUrl: 'https://paper-roll-nine.vercel.app/',
        githubUrl: 'https://github.com/thebuggeddev/paper-roll',
        image: HOST + 'images/paper-roll.webp',
      },
      {
        id: 'vinyl',
        name: 'vinyl',
        name_en: 'vinyl',
        tip: '使用Three.js开发的交互式三维黑胶唱片机展示作品。',
        author: 'AUTO',
        openUrl: 'https://vinyl-rho-peach.vercel.app/',
        githubUrl: 'https://github.com/thebuggeddev/vinyl',
        image: HOST + 'images/vinyl.webp',
      },
      {
        id: 'three-stylized',
        name: 'three-stylized',
        name_en: 'three-stylized',
        tip: '程序化生成草地与野花，带风动和风格化光照的渲染场景',
        author: 'AUTO',
        openUrl: 'https://steve245270533.github.io/three-stylized/',
        githubUrl: 'https://github.com/Steve245270533/three-stylized',
        image: HOST + 'images/three-stylized.webp',
      },
      {
        id: 'complete-shelf',
        name: 'complete-shelf',
        name_en: 'The Complete Shelf',
        tip: '交互式三维书架，可浏览、拉出并翻动布面精装书',
        author: 'AUTO',
        openUrl: 'https://mengto.github.io/complete-shelf/',
        githubUrl: 'https://github.com/MengTo/complete-shelf',
        image: HOST + 'images/complete-shelf.webp',
      },
      {
        id: 'prehistoric-animal-museum',
        name: 'prehistoric-animal-museum',
        name_en: 'A quiet place to look closely',
        tip: '史前动物虚拟博物馆，提供双语解说与亲子导览',
        author: 'AUTO',
        openUrl: 'https://leon-made-this.work/museum',
        githubUrl: 'https://github.com/s010s/prehistoric-animal-museum',
        image: HOST + 'images/prehistoric-animal-museum.jpg',
      },
      {
        id: 'locker-folio',
        name: 'locker-folio',
        name_en: 'Locker Folio',
        tip: '交互式个人作品集，以储物柜为载体，物件对应不同板块。',
        author: 'AUTO',
        openUrl: 'https://locker.zezn.dev/',
        githubUrl: 'https://github.com/qzz0518/locker-folio',
        image: HOST + 'images/locker-folio.webp',
      },
      {
        id: 'human-atlas',
        name: 'human-atlas',
        name_en: 'Human Atlas',
        tip: '交互式3D人体解剖探索器，可拆解成人男性模型，查看骨骼和器官系统。',
        author: 'AUTO',
        openUrl: 'https://human-atlas-seven.vercel.app/',
        githubUrl: 'https://github.com/ashemag/human-atlas',
        image: HOST + 'images/human-atlas.webp',
      },
      {
        id: 'gpt6-Astra',
        name: 'gpt6-Astra',
        name_en: 'gpt6-Astra_3.js',
        tip: '六个使用Three.js制作的交互式微缩场景，均为独立HTML文件，无需',
        author: 'AUTO',
        openUrl: 'https://github.com/XinyuWang250428/gpt6-Astra_3.js',
        githubUrl: 'https://github.com/XinyuWang250428/gpt6-Astra_3.js',
        image: HOST + 'images/gpt6-Astra.webp',
      },
      {
        id: 'qingmingshanghetu',
        name: '入画·汴京｜GPT-6 Astra 实践测试',
        name_en: '入画·汴京｜GPT-6 Astra 实践测试',
        tip: '将清明上河图虹桥与市井做成可交互三维网页，支持点击探索与录制。',
        author: 'AUTO',
        openUrl: 'https://rising1234sun.github.io/qingmingshanghetu/',
        githubUrl: 'https://github.com/Rising1234Sun/qingmingshanghetu',
        image: HOST + 'images/qingmingshanghetu.webp',
      },
      {
        id: 'qingmingsa',
        name: '清明上河 · Qingming Riverside',
        name_en: '清明上河 · Qingming Riverside',
        tip: '清明上河图三维场景开发项目，需使用Git LFS拉取大型资源文件。',
        author: 'AUTO',
        openUrl: 'https://qingming-riverside.vercel.app/',
        githubUrl: 'https://github.com/mike007jd/qingming',
        image: HOST + 'images/qingmingsa.webp',
      },
      {
        id: 'iphone-duo',
        name: 'iphone-duo',
        name_en: 'iPhone Duo · Fold Preview',
        tip: '基于Three.js研究可折叠屏幕过渡效果的浏览器端交互演示。',
        author: 'AUTO',
        openUrl: 'https://iphone-duo-tawny.vercel.app/',
        githubUrl: 'https://github.com/chuspeeism/iphone-duo',
        image: HOST + 'images/iphone-duo.webp',
      },
      {
        id: 'insect-world',
        name: '昆虫世界',
        name_en: '昆虫世界',
        tip: '展示昆虫生态的三维场景作品',
        author: 'AUTO',
        openUrl: 'https://insect-world.pages.dev/s/monarch-butterfly/',
        githubUrl: 'https://github.com/xr843/insect-world',
        image: HOST + 'images/insect-world.webp',
      },
      {
        id: 'sylva',
        name: 'sylva',
        name_en: 'Sylva',
        tip: '程序化苔藓树根随指针反应的交互景观研究',
        author: 'AUTO',
        openUrl: 'https://mengto.github.io/sylva/',
        githubUrl: 'https://github.com/MengTo/sylva',
        image: HOST + 'images/sylva.webp',
      },
      {
        id: 'Transformers',
        name: 'Transformers',
        name_en: 'Transformers',
        tip: '沙漠中停驻卡车的三维场景叙事展示',
        author: 'AUTO',
        openUrl: 'https://transformer.scottsun.io/',
        githubUrl: 'https://github.com/scottstts/Transformers',
        image: HOST + 'images/Transformers.webp',
      },
      {
        id: 'MengTokage',
        name: 'MengTokage',
        name_en: 'Kage',
        tip: '京都山寺五章夜游交互式三维体验',
        author: 'AUTO',
        openUrl: 'https://mengto.github.io/kage/',
        githubUrl: 'https://github.com/MengTo/kage',
        image: HOST + 'images/MengTokage.webp',
      },
      {
        id: 'endless-train',
        name: 'endless-train',
        name_en: 'endless-train',
        tip: '用三维技术呈现无尽列车旅行艺术场景，可沉浸式观赏沿途风光。',
        author: 'AUTO',
        openUrl: 'https://endless-train.wasmer.app/',
        githubUrl: 'https://github.com/thebuggeddev/endless-train',
        image: HOST + 'images/endless-train.jpg',
      },
      {
        id: 'pc-anatomy',
        name: 'pc-anatomy',
        name_en: 'PC Anatomy',
        tip: '开源三维电脑解剖探索器，从整机到芯片逐层拆解展示硬件结构。',
        author: 'AUTO',
        openUrl: 'https://pc-anatomy.com/',
        githubUrl: 'https://github.com/Yoosseph/pc-anatomy',
        image: HOST + 'images/pc-anatomy.webp',
      }
    ],
  },
  {
    pid: 'threejsSource',
    name: '扩展依赖',
    name_en: 'Dependency',
    gid: 'ecologyExpand',
    group: '生态扩展',
    group_en: 'Ecology Expand',
    order: 60,
    children: [
      {
        id: 'r3f-webgpu-post-processing',
        name: 'webgpu 后期渲染',
        name_en: 'React Three Fiber WebGPU Post Processing',
        tip: '基于React Three Fiber的WebGPU后处理示例，展示高级',
        author: 'AUTO',
        openUrl: 'https://r3f-webgpu-post-processing.vercel.app/',
        githubUrl: 'https://github.com/ektogamat/r3f-webgpu-starter',
        image: HOST + 'images/r3f-webgpu-post-processing.webp',
      },
      {
        id: 'FluffyGrass',
        name: '草地',
        name_en: 'ThreejsGrass',
        tip: 'Three.js实现的高性能蓬松草地效果，附带免费教程，适合学习渲染技巧',
        author: 'AUTO',
        openUrl: 'https://fluffygrass.vercel.app/',
        githubUrl: 'https://github.com/thebenezer/FluffyGrass',
        image: HOST + 'images/FluffyGrass.webp',
      },
      {
        id: 'wawa-baking',
        name: '烘培房间',
        name_en: 'R3F Baking Tutorial for Three.js',
        tip: 'React Three Fiber烘焙教程，展示Three.js模型烘焙',
        author: 'AUTO',
        openUrl: 'https://baking.wawasensei.dev/',
        githubUrl: 'https://github.com/wass08/r3f-baking',
        image: HOST + 'images/wawa-baking.webp',
      },
      {
        id: 'codrops-noise-transition',
        name: '易拉罐',
        name_en: 'Model Texture Transition And Procedural Radial N',
        tip: 'WebGL实验展示三维罐子模型纹理过渡和程序化径向噪声场效果。',
        author: 'AUTO',
        openUrl: 'https://tympanus.net/Development/TextureTransition/',
        githubUrl: 'https://github.com/mohAmineBrs/codrops-noise-transition/',
        image: HOST + 'images/codrops-noise-transition.webp',
      },
      {
        id: 'hologram-particles',
        name: 'hologram-particles',
        name_en: 'Hologram Particles VFX',
        tip: '基于WebGPU和TSL着色器的全息粒子特效库。',
        author: 'AUTO',
        openUrl: 'https://hologram-particles.vercel.app/',
        githubUrl: 'https://github.com/cortiz2894/hologram-particles',
        image: HOST + 'images/hologram-particles.webp',
      },
      {
        id: 'three-fenestra',
        name: 'three-fenestra',
        name_en: 'Three-Fenestra: an interior mapping shader for T',
        tip: '为平面窗户添加视差假三维房间的着色器材质，支持窗帘百叶窗等细节。',
        author: 'AUTO',
        openUrl: 'https://three-fenestra.codedgar.com/',
        githubUrl: 'https://github.com/codedgar/three-fenestra',
        image: HOST + 'images/three-fenestra.webp',
      },
      {
        id: 'dtilesConverter',
        name: '3dtiles Converter',
        name_en: '3dtiles Converter',
        tip: '将三维模型转换为3D Tiles格式的工具，支持多种平台和自动化构建。',
        author: 'AUTO',
        openUrl: 'https://github.com/fanvanzh/3dtiles',
        githubUrl: 'https://github.com/fanvanzh/3dtiles',
        image: HOST + 'images/dtilesConverter.webp',
      },
      {
        id: 'webgpu-perf',
        name: 'webgpu-perf',
        name_en: 'r3f-webgpu-perf',
        tip: '用于React Three Fiber的WebGPU性能监控工具，帮助优',
        author: 'AUTO',
        openUrl: 'https://r3f-webgpu-perf.vercel.app/',
        githubUrl: 'https://github.com/ektogamat/r3f-webgpu-perf',
        image: HOST + 'images/webgpu-perf.webp',
      },
      {
        id: 'Lens-Flare',
        name: 'Lens-Flare',
        name_en: 'ULTIMATE LENS FLARE FOR REACT THREE FIBER',
        tip: '为React Three Fiber提供终极镜头光晕效果的组件库，增强视',
        author: 'AUTO',
        openUrl: 'https://ultimate-lens-flare.vercel.app/',
        githubUrl: 'https://github.com/ektogamat/R3F-Ultimate-Lens-Flare',
        image: HOST + 'images/Lens-Flare.webp',
      },
      {
        id: 'openThree',
        name: '开源三维',
        name_en: '💎 Three.js 和 Cesium.js 案例 - 为爱发电 - 只做开源 -',
        tip: '开源Three.js和Cesium.js案例仓库，持续更新，提供丰富示例',
        author: 'AUTO',
        openUrl: 'https://z2586300277.github.io/three-cesium-examples',
        githubUrl: 'https://github.com/z2586300277/three-cesium-examples',
        image: HOST + 'images/openThree.webp',
      },
      {
        id: '3d_tools',
        name: '3D相关工具集',
        name_en: '3d_tools',
        tip: '在线3D工具集合，提供GLB转MIN等格式转换功能，方便开发者使用。',
        author: 'AUTO',
        openUrl: 'https://z2586300277.github.io/3d_tools/',
        githubUrl: 'https://github.com/z2586300277/3d_tools',
        image: HOST + 'images/3d_tools.webp',
      },
      {
        id: 'ecctrl_ecctrl',
        name: 'ecctrl_ecctrl',
        name_en: 'Ecctrl',
        tip: '基于React Three Fiber和Rapier的控制器库，用于实现',
        author: 'AUTO',
        openUrl: 'https://ecctrl.app/',
        githubUrl: 'https://github.com/pmndrs/ecctrl',
        image: HOST + 'images/ecctrl_ecctrl.webp',
      },
      {
        id: 'collider-forge',
        name: 'collider-forge',
        name_en: 'collider-forge',
        tip: '可视化工具，加载多种3D数据生成碰撞网格并导出GLB碰撞体。',
        author: 'AUTO',
        openUrl: 'https://github.com/hh-hang/collider-forge',
        githubUrl: 'https://github.com/hh-hang/collider-forge',
        image: HOST + 'images/collider-forge.webp',
      },
      {
        id: 'cesium-player-controller',
        name: 'cesium 第三人称控制器',
        name_en: 'cesium-player-controller',
        tip: 'Cesium玩家控制器，处理地形和3D Tiles碰撞，需配合colli',
        author: 'AUTO',
        openUrl: 'https://hh-hang.github.io/cesium-player-controller/',
        githubUrl: 'https://github.com/hh-hang/cesium-player-controller',
        image: HOST + 'images/cesium-player-controller.webp',
      },
      {
        id: 'cesium-ez-tree',
        name: 'cesium-ez-tree',
        name_en: 'cesium-ez-tree',
        tip: '基于Cesium的简易树形控件库，方便构建三维场景图层管理',
        author: 'AUTO',
        openUrl: 'https://xiaobai-grow.github.io/cesium-ez-tree/',
        githubUrl: 'https://github.com/Xiaobai-grow/cesium-ez-tree',
        image: HOST + 'images/cesium-ez-tree.webp',
      },
      {
        id: 'threejswaterpro',
        name: 'threejswaterpro',
        name_en: 'threejswaterpro',
        tip: 'Three.js水面效果扩展库，提供逼真水体渲染与交互能力',
        author: 'AUTO',
        openUrl: 'https://www.threejswaterpro.com/',
        githubUrl: 'https://github.com/dgreenheck/webgpu-water',
        image: HOST + 'images/threejswaterpro.webp',
      },
      {
        id: 'tellux',
        name: 'tellux',
        name_en: 'Tellux',
        tip: '轻量级三维渲染工具库，封装常用图形功能便于快速开发',
        author: 'AUTO',
        openUrl: 'https://tellux.cyanfish.site/sandcastle.html',
        githubUrl: 'https://github.com/cyanfish-x/tellux',
        image: HOST + 'images/tellux.webp',
      },
      {
        id: 'cyanfishcesium',
        name: 'cyanfish-cesium',
        name_en: 'cyanfish-cesium',
        tip: '基于Cesium的三维可视化工具库，提供场景构建辅助功能',
        author: 'AUTO',
        openUrl: 'https://demo.cyanfish.site/cesium',
        githubUrl: 'https://github.com/cyanfish-x/tellux',
        image: HOST + 'images/cyanfishcesium.webp',
      },
      {
        id: 'lego-stylized-nature',
        name: 'lego-stylized-nature',
        name_en: 'Three.js TSL template',
        tip: 'Three.js着色语言模板，帮助初学者练习TSL着色器编写',
        author: 'AUTO',
        openUrl: 'https://lego-stylized-nature.vercel.app/',
        githubUrl: 'https://github.com/hexianWeb/lego-stylized-nature',
        image: HOST + 'images/lego-stylized-nature.webp',
      },
      {
        id: 'collectivetrajectories',
        name: 'collectivetrajectories',
        name_en: 'Collective Trajectories',
        tip: '基于计算着色器的球面纤维轨迹实时可视化技术演示项目',
        author: 'AUTO',
        openUrl: 'https://jeonghopark.de/collectivetrajectories/',
        githubUrl: 'https://github.com/jeonghopark/Collective-Trajectories',
        image: HOST + 'images/collectivetrajectories.jpg',
      },
      {
        id: 'threejsskypro',
        name: 'threejsskypro',
        name_en: 'threejsskypro',
        tip: '提供天空与大气渲染效果的扩展库，可模拟真实天光环境',
        author: 'AUTO',
        openUrl: 'https://threejsskypro.com/',
        githubUrl: 'https://github.com/threejsskypro/threejsskypro',
        image: HOST + 'images/threejsskypro.webp',
      },
      {
        id: 'silhouette-pom',
        name: 'silhouette-pom',
        name_en: 'Silhouette Parallax Occlusion Mapping for three.',
        tip: '视差遮蔽贴图扩展，通过高度图雕刻模型轮廓增强表面细节',
        author: 'AUTO',
        openUrl: 'https://skyeshark.github.io/threejs-silhouette-pom/',
        githubUrl: 'https://github.com/SkyeShark/threejs-silhouette-pom',
        image: HOST + 'images/silhouette-pom.webp',
      },
      {
        id: 'challenge-geo',
        name: 'challenge-geo',
        name_en: 'x challenge geo',
        tip: '受几何节点启发的三维几何体生成与编辑实验项目',
        author: 'AUTO',
        openUrl: 'https://x-challenge-geo.vercel.app/',
        githubUrl: 'https://github.com/wehwayne2/x-challenge-geo',
        image: HOST + 'images/challenge-geo.webp',
      },
      {
        id: 'TerrainStudio',
        name: 'TerrainStudio',
        name_en: 'Terrain Studio',
        tip: '程序化地形生成器，基于Three.js和着色器实现。',
        author: 'AUTO',
        openUrl: 'https://terrains.zyfod.dev/',
        githubUrl: 'https://github.com/nalbam/TerrainStudio',
        image: HOST + 'images/TerrainStudio.webp',
      },
      {
        id: 'lowpoly-tree-generator',
        name: 'lowpoly-tree-generator',
        name_en: 'Lowpoly Tree Generator',
        tip: '参数化低多边形树木生成器，输出单一几何体。',
        author: 'AUTO',
        openUrl: 'https://rand.monster/editor/tree',
        githubUrl: 'https://github.com/rand-monster/lowpoly-tree-generator',
        image: HOST + 'images/lowpoly-tree-generator.webp',
      },
      {
        id: 'gltf-optimizer',
        name: '模型压缩',
        name_en: '[Demo](https://juunini.github.io/gltf-optimizer)',
        tip: '压缩GLB文件的在线工具，未来将支持GLTF格式',
        author: 'AUTO',
        openUrl: 'https://gltf-optimizer.simondev.io/',
        githubUrl: 'https://github.com/juunini/gltf-optimizer',
        image: HOST + 'images/gltf-optimizer.webp',
      },
      {
        id: 'SeedOcean',
        name: 'SeedOcean',
        name_en: 'SeedOcean',
        tip: '开源FFT海洋系统，优先WebGPU并回退WebGL2',
        author: 'AUTO',
        openUrl: 'https://reed-soul.github.io/SeedOcean/',
        githubUrl: 'https://github.com/reed-soul/SeedOcean',
        image: HOST + 'images/SeedOcean.webp',
      },
      {
        id: 'three-auto',
        name: 'three-auto',
        name_en: 'Install',
        tip: '快速生成Three.js场景的库，自动配置相机渲染器',
        author: 'AUTO',
        openUrl: 'https://three-auto.vercel.app/',
        githubUrl: 'https://github.com/flowers-10/three-auto',
        image: HOST + 'images/three-auto.webp',
      },
      {
        id: 'waterProThree',
        name: 'waterProThree',
        name_en: 'WaterThreeJS',
        tip: '基于Three.js的实时海洋渲染，程序化生成波浪、天空与焦散效果。',
        author: 'AUTO',
        openUrl: 'https://g2657.github.io/examples-server/waterPro/',
        githubUrl: 'https://github.com/achrefelouafi/WaterThreeJS',
        image: HOST + 'images/waterProThree.webp',
      },
      {
        id: 'ProceduralTerrains',
        name: '地形生成',
        name_en: 'Procedural Terrains',
        tip: '浏览器端GPU驱动的地形创作工具，支持Unity和Blender原生集成',
        author: 'AUTO',
        openUrl: 'https://terrains.zyfod.dev/',
        githubUrl: 'https://github.com/ZyFou/ProceduralTerrains',
        image: HOST + 'images/ProceduralTerrains.webp',
      },
      {
        id: 'three-low-poly',
        name: 'three-low-poly',
        name_en: 'Three.js Low Poly',
        tip: '为Three.js提供低多边形程序化工具与参数化建模能力。',
        author: 'AUTO',
        openUrl: 'https://jasonsturges.com/three-low-poly/',
        githubUrl: 'https://github.com/jasonsturges/three-low-poly',
        image: HOST + 'images/three-low-poly.webp',
      },
      {
        id: 'GrassSystemThreeJS',
        name: 'GrassSystemThreeJS',
        name_en: 'Soil Studio',
        tip: '实时程序化土壤沙盒，GPU重塑地形并搭配电影级后期处理。',
        author: 'AUTO',
        openUrl: 'https://github.com/achrefelouafi/GrassSystemThreeJS',
        githubUrl: 'https://github.com/achrefelouafi/GrassSystemThreeJS',
        image: HOST + 'images/GrassSystemThreeJS.webp',
      },
      {
        id: 'SnowSystemThreeJS',
        name: 'SnowSystemThreeJS',
        name_en: 'Snow System (Three.js)',
        tip: '全程序化雪景工作室，模拟降雪与地面积雪，复用雨系统架构。',
        author: 'AUTO',
        openUrl: 'https://g2657.github.io/SnowSystemThreeJS/',
        githubUrl: 'https://github.com/achrefelouafi/SnowSystemThreeJS',
        image: HOST + 'images/SnowSystemThreeJS.webp',
      },
      {
        id: 'BuildingGeneratorThreeJS',
        name: 'BuildingGeneratorThreeJS',
        name_en: 'BuildingGeneratorThreeJS',
        tip: '从Blender几何节点移植的香港建筑程序化生成器，用于Three.js',
        author: 'AUTO',
        openUrl: 'https://github.com/achrefelouafi/BuildingGeneratorThreeJS',
        githubUrl: 'https://github.com/achrefelouafi/BuildingGeneratorThreeJS',
        image: HOST + 'images/BuildingGeneratorThreeJS.webp',
      },
      {
        id: 'threeui',
        name: 'threeui',
        name_en: 'ThreeUI Community',
        tip: 'Three.js的UI组件库，提供赞助计划与文档。',
        author: 'AUTO',
        openUrl: 'https://threeui.com/',
        githubUrl: 'https://github.com/MengTo/threeui',
        image: HOST + 'images/threeui.webp',
      },
      {
        id: 'beautiful-water',
        name: 'beautiful-water',
        name_en: 'Beautiful Water',
        tip: '一个实现美丽水面效果的开源库，包含持续集成和部署配置。',
        author: 'AUTO',
        openUrl: 'https://victorzakharov.github.io/beautiful-water/',
        githubUrl: 'https://github.com/VictorZakharov/beautiful-water',
        image: HOST + 'images/beautiful-water.webp',
      },
      {
        id: 'Ai-three-ui',
        name: '复制提示词生成3D',
        name_en: 'ThreeUI Community',
        tip: 'ThreeUI是一个用户界面库，提供赞助计划，用于支持项目发展。',
        author: 'AUTO',
        openUrl: 'https://threeui.com/browse',
        githubUrl: 'https://github.com/MengTo/threeui',
        image: HOST + 'images/Ai-three-ui.webp',
      }
    ],
  },
  {
    pid: 'framework',
    name: '相关框架',
    name_en: 'Frame Work',
    gid: 'ecologyExpand',
    group: '生态扩展',
    group_en: 'Ecology Expand',
    order: 60,
    children: [
      {
        id: 'pixijs',
        name: 'pixijs',
        name_en: 'PixiJS ⚡️',
        tip: 'PixiJS是一个强大的2D渲染框架，提供指南、教程、示例和API文档。',
        author: 'AUTO',
        openUrl: 'https://pixijs.com/showcase',
        githubUrl: 'https://github.com/pixijs/pixijs',
        image: HOST + 'images/pixijs.webp',
      },
      {
        id: 'MisterPrada',
        name: 'MisterPrada',
        name_en: 'singularity',
        tip: '提供安装运行命令的Three.js项目模板',
        author: 'AUTO',
        openUrl: 'https://github.com/MisterPrada',
        githubUrl: 'https://github.com/MisterPrada/singularity',
        image: HOST + 'images/MisterPrada.webp',
      },
      {
        id: 'anatomy-atelier',
        name: 'anatomy-atelier',
        name_en: 'vinext-starter',
        tip: '全栈起步模板，集成可选数据库与数据映射支持',
        author: 'AUTO',
        openUrl: 'https://anatomy-livid.vercel.app/',
        githubUrl: 'https://github.com/thebuggeddev/anatomy',
        image: HOST + 'images/anatomy-atelier.webp',
      }
    ],
  },
  {
    pid: 'ortherSource',
    name: '其他资源',
    name_en: 'Other Resources',
    order: 90,
    children: [
      {
        id: 'texturesFree',
        name: '免费贴图',
        name_en: 'texturesFree',
        tip: '提供免费三维贴图素材资源，供场景模型纹理使用',
        author: 'AUTO',
        openUrl: 'https://www.textures.com/free',
        githubUrl: 'https://github.com/textures/textures',
        image: HOST + 'images/texturesFree.webp',
      },
      {
        id: 'geo-downloader',
        name: '地区geo-下载器',
        name_en: '下载安装',
        tip: '地理数据下载工具，提供便捷的安装与使用指南。',
        author: 'AUTO',
        openUrl: 'https://geodownloader.pages.dev/',
        githubUrl: 'https://github.com/gaopengbin/geo-downloader',
        image: HOST + 'images/geo-downloader.webp',
      },
      {
        id: 'fmhy',
        name: '资源库',
        name_en: 'FMHY',
        tip: '互联网免费资源集合，非三维相关项目。',
        author: 'AUTO',
        openUrl: 'https://fmhy.net/',
        githubUrl: 'https://github.com/fmhy/edit',
        image: HOST + 'images/fmhy.webp',
      },
      {
        id: 'meteor3D',
        name: '低代码 3D 场景可视化平台',
        name_en: 'Meteor3D',
        tip: 'Meteor3D项目官网演示，展示功能特性与技术栈信息。',
        author: 'AUTO',
        openUrl: 'https://www.meteor3d.cn/',
        githubUrl: 'https://github.com/nikonikoCW/Meteor3DEditor',
        image: HOST + 'images/meteor3D.webp',
      },
      {
        id: 'achrefelouafi',
        name: 'achrefelouafi',
        name_en: 'achrefelouafi',
        tip: '个人作品集网站，展示三维创意与开发项目。',
        author: 'AUTO',
        openUrl: 'https://chirostudio.xyz/',
        githubUrl: 'https://github.com/achrefelouafi/achrefelouafi',
        image: HOST + 'images/achrefelouafi.webp',
      },
      {
        id: 'voidrunner-astra',
        name: 'voidrunner-astra',
        name_en: 'Bench Portal',
        tip: 'AI生成游戏与三维展示的静态目录，支持分类搜索与过滤。',
        author: 'AUTO',
        openUrl: 'https://alesha-pro.github.io/bench-portal/games/voidrunner-astra/',
        githubUrl: 'https://github.com/alesha-pro/bench-portal/tree/main/games/voidrunner-astra',
        image: HOST + 'images/voidrunner-astra.webp',
      },
      {
        id: 'bench-portal',
        name: 'ai 浏览器游戏',
        name_en: 'Bench Portal',
        tip: '一个静态目录网站，收录人工智能生成的游戏、三维展示和着色器实验，支持分类',
        author: 'AUTO',
        openUrl: 'https://alesha-pro.github.io/bench-portal/',
        githubUrl: 'https://github.com/alesha-pro/bench-portal',
        image: HOST + 'images/bench-portal.webp',
      },
      {
        id: 'grassMisterPrada',
        name: 'grassMisterPrada',
        name_en: 'grass',
        tip: '一个项目模板，提供安装和运行命令，帮助快速启动开发环境。',
        author: 'AUTO',
        openUrl: 'https://grass.misterprada.com/',
        githubUrl: 'https://github.com/MisterPrada/grass',
        image: HOST + 'images/grassMisterPrada.jpg',
      }
    ],
  }
]
