export default [
    {
        pid: 'RecentlySubmitted',
        name: '最近提交',
        name_en: 'Recently Submitted',
        order: 0,
        children: [
            {
                id: 'LearningCell',
                name: '细胞课堂',
                name_en: 'LearningCell',
                author: 'AUTO',
                openUrl: 'https://gordensun.github.io/LearningCell/',
                githubUrl: 'https://github.com/GordenSun/LearningCell',
                image: HOST + 'images/LearningCell.webp',
            },
{
                id: 'PSU-VR',
                name: '室内vr',
                name_en: 'PSU-VR',
                author: 'AUTO',
                openUrl: 'https://psu-vr.herokuapp.com/',
                githubUrl: 'https://github.com/andrewwoan/PSU-VR',
                image: HOST + 'images/PSU-VR.webp',
            },
            {
                id: 'sooahs-room-folio',
                name: '房间',
                name_en: 'sooahs-room-folio',
                author: 'AUTO',
                openUrl: 'https://www.sooahs-room-folio.com/',
                githubUrl: 'https://github.com/andrewwoan/sooahs-room-folio',
                image: HOST + 'images/sooahs-room-folio.webp',
            },
{
                id: 'r3f-webgpu-post-processing',
                name: 'webgpu 后期渲染',
                name_en: 'r3f-webgpu-post-processing',
                author: 'AUTO',
                openUrl: 'https://r3f-webgpu-post-processing.vercel.app/',
                githubUrl: 'https://github.com/ektogamat/r3f-webgpu-starter',
                image: HOST + 'images/r3f-webgpu-post-processing.webp',
            },
{
                id: 'DeviceShowcase',
                name: '电脑',
                name_en: 'DeviceShowcase',
                author: 'AUTO',
                openUrl: 'https://tympanus.net/Tutorials/DeviceShowcase/',
                githubUrl: 'https://github.com/repalash/threepipe-device-mockup-codrops',
                image: HOST + 'images/DeviceShowcase.webp',
            },
{
                id: 'bellas-park',
                name: '公园',
                name_en: 'bellas-park',
                author: 'AUTO',
                openUrl: 'https://www.bellas-park.com/',
                githubUrl: 'https://github.com/andrewwoan/bellas-park',
                image: HOST + 'images/bellas-park.webp',
            },
{
                id: 'FluffyGrass',
                name: '草地',
                name_en: 'FluffyGrass',
                author: 'AUTO',
                openUrl: 'https://fluffygrass.vercel.app/',
                githubUrl: 'https://github.com/thebenezer/FluffyGrass',
                image: HOST + 'images/FluffyGrass.webp',
            },
            {
                id: 'wawa-baking',
                name: '烘培房间',
                name_en: 'wawa-baking',
                author: 'AUTO',
                openUrl: 'https://baking.wawasensei.dev/',
                githubUrl: 'https://github.com/wass08/r3f-baking',
                image: HOST + 'images/wawa-baking.webp',
            },
            {
                id: 'codrops-noise-transition',
                name: '易拉罐',
                name_en: 'codrops-noise-transition',
                author: 'AUTO',
                openUrl: 'https://tympanus.net/Development/TextureTransition/',
                githubUrl: 'https://github.com/mohAmineBrs/codrops-noise-transition/',
                image: HOST + 'images/codrops-noise-transition.webp',
            },
            {
                id: 'zen-robot-garden',
                name: '割草机器人',
                name_en: 'zen-robot-garden',
                author: 'AUTO',
                openUrl: 'https://robin7331.github.io/zen-robot-garden/',
                githubUrl: 'https://github.com/robin7331/zen-robot-garden',
                image: HOST + 'images/zen-robot-garden.webp',
            },
            {
                id: 'pmndrs',
                name: 'pmndrs 作品库',
                name_en: 'pmndrs',
                author: 'AUTO',
                openUrl: 'https://pmnd.rs/',
                githubUrl: 'https://github.com/pmndrs/ react-three-fiber',
                image: HOST + 'images/pmndrs.webp',
            },
        ]
    }
]